### ISSUE TITLE
Formatting guidelines with Black

### ISSUE THREAD

**Issue by rhthomas** [devAmoghS/Python-Interview-Problems-for-Practice#8]
In the readme it says:
> It passes style checks (PEP8 compliant) [TODO]

Would it be better to auto format all files with [Black](https://github.com/python/black)? This means dev's won't need to manually check for PEP8 compliance.

**Comment by devAmoghS** [comment]
Let me have a look at it. I have not used it before though.

**Comment by devAmoghS** [comment]
@rhthomas Please go ahead with raising the PR for making the changes. I will merge it after review. We need more contributors for this project.
