### ISSUE TITLE
Inefficient BST_nodes_in_range.py

### ISSUE THREAD

**Issue by Bogdy2** [devAmoghS/Python-Interview-Problems-for-Practice#9]
If using greater than or equal too and less than or equal to in line 14, then you can remove the check to see if it is ever equal to the max or the low range. So you can remove the lines 16 and 17.

**Comment by devAmoghS** [comment]
@Bogdy2 Thank you for raising this issue. Please go ahead with raising the PR for making the changes. I will merge it after review. We need more contributors for this project!
